name: Texter
main: Texter\Main
version: 2.1.9
api:
  - 3.0.0
  - 3.0.0-ALPHA5
  - 3.0.0-ALPHA6
  - 3.0.0-ALPHA7 #pmmp/PocketMine-MP
author: yuko fuyutsuki
authors:
# SpecialThanks(敬称略)
 - mfmfnek0
 - onebone
 - ogiwara
 - Shootsta_ERU0531
 - Toganon
 - ShadowArt
 - Marron0421
website: https://twitter.com/y_fyi

permissions:
 texter.*:
  default: op
  description: "permission that allows player to use texter"
  children:
   texter.command.*:
    default: op
    description: "permission that allows player to use texter"
    children:
      texter.command.txt:
        default: op
        description: "permission that allows player to use /txt"
      texter.command.txtadm:
        default: op
        description: "permission that allows player to use /txtadm"
