configVersion: 20

# 日本語 ガイド
# eng guide

# Texter 設定ファイル
# Texter config file

# 言語を設定してください (eng or jpn)
# set language (eng or jpn)
language: jpn

# タイムゾーンを設定してください
# set timezone
timezone: Asia/Tokyo

# もし起動時にアップデートの通知が必要ならtrue, 必要ないならfalseにしてください
# When set to true, update notification is displayed at startup
checkUpdate: true

# コマンドを使用不可にしたい場合はfalseにしてください
# If you want to disable the command, prease set it to false
canUseCommands: true

# Write "new" if the path to Add/RemoveEntityPacket is
# pocketmine\network\mcpe\protocol\...,
# if not, please write "old".

# Add/RemoveEntityPacketのパスが
# pocketmine\newwork\mcpe\protocol\...なら"new"と記載し、
# そうでなければ"old"と記載して下さい。
path: new

# 文字数の制限をする場合は文字数を, 不要なら -1 にしてください
# To limit the number of characters, set the number of characters, if unnecessary, set it to -1.
limit: 50
